const upcommingcourses = [
    {name:'Ruby on rails',
     price:'250',
     img:'https://aldibs.com/wp-content/uploads/2020/01/ruby-on-rails-development.jpg',
     description:'Ruby on Rails is an open-source software used to build web applications. Rails is a framework used to create websites using the general-purpose programming language Ruby. Ruby ranks amongst the top ten programming languages predominantly because of the voguishness of Rails.',
     duration:'Estimated 7 weeks.(2–4 hours per week)',
    },
    {name:'C#',
    price:'100',
    img:'https://pluralsight.imgix.net/paths/path-icons/csharp-e7b8fcd4ce.png',
    description:'C# is widely used for developing desktop applications, web applications and web services. It is used in creating applications of Microsoft at a large scale. C# is also used in game development in Unity.',
    duration:'Estimated 5 weeks.(2–3 hours per week)',
   },
   {name:'IOT',
   price:'250',
   img:'https://news.mit.edu/sites/default/files/styles/news_article__image_gallery/public/images/202011/MIT-Tiny-AI-01_0.jpg?itok=chf7f8K1',
   description:'The Internet of Things (IoT) describes the network of physical objects—“things”—that are embedded with sensors, software, and other technologies for the purpose of connecting and exchanging data with other devices and systems over the internet.',
   duration:'Estimated 7 weeks.(2–4 hours per week)',
  },
  {name:'React Native',
  price:'200',
  img:'https://pagepro.co/blog/wp-content/uploads/2020/03/react-native-logo-884x1024.png',
  description:'Let it be clear that this development tool is not dead; even in 2021. However, there may be other rivals, such as Flutter and Kotlin, who are attempting to take their position, however, React Native is capable of generating excellent applications, and Facebook is working hard to ensure that it does not become obsolete',
  duration:'Estimated 4 weeks.(2–4 hours per week)',
 },
 {name:'TypeScript',
 price:'200',
 img:'https://serokell.io/files/0u/0ufu1q21.js-ts.jpg',
 description:'TypeScript may be used to develop JavaScript applications for both client-side and server-side execution (as with Node. js or Deno). There are multiple options available for transcompilation. Either the default TypeScript Checker can be used, or the Babel compiler can be invoked to convert TypeScript to JavaScript.',
 duration:'Estimated 4 weeks.(2–4 hours per week)',
},
]